.github/pull_request_template.md
as title
-----------------
Clickup task URL: https://app.clickup.com/t/<abcdefg>
-----------------
補充說明:
=> modify the current PR template

src/main.cpp, src/windows/mainwindow.cpp, src/windows/mainwindow.h
Add define ENABLE_SENTRY for user to give dsn
define ENABLE_SENTRY or not in qt creator to disable sentry
=> Add define ENABLE_SENTRY for user to give dsn

CMakeLists.txt
Add option for cmake to enable sentry. Turn off sentry by default.
=> Update CMakeLists.txt for sentry option

src/canvas/controls/line.cpp, src/canvas/controls/path-draw.cpp, src/canvas/controls/transform.cpp
**路徑繪製 物件移動&旋轉 直線繪製 增加45度控制**
-----------------
Clickup task URL: https://app.clickup.com/t/3c0bqjh<abcdefg>
-----------------
補充說明:
=> Add direction control by 45 degrees

src/canvas/canvas.cpp, src/windows/preview-window.cpp
**Change wheel control to update scale only**
-----------------
Clickup task URL: https://app.clickup.com/t/3c0c5up<abcdefg>
-----------------
補充說明:
=> Change wheel control to update scale only

src/windows/mainwindow.cpp
**Add drop file for .dxf**
-----------------
Clickup task URL: https://app.clickup.com/t/3c0bqm0<abcdefg>
-----------------
補充說明:
=> Add drop file for .dxf

src/canvas/canvas.cpp
Add cursor change when holdong space and transform shape.
Holding space to see the cursor change.
=> Add cursor change when holding space and transform shape

src/canvas/controls/select.cpp
Add check layer when multi select.
Change active layer when select layer are the same.
=> Add check layer when multi select

src/canvas/controls/select.cpp
Fix bug when select without shape.
Multi-select with nothing.
=> Fix bug when select without shape

src/canvas/canvas.cpp, src/windows/mainwindow.cpp
Change the input svg file size.
Input svg (3mm ruler) to check the size is 3cm.
=> resize the svg file

src/canvas/canvas.cpp, src/windows/mainwindow.cpp
Fix bug of click change scale & wheel change scale.
Click scale change to 3% and increase scale, use wheel and control to change scale small than 10%
=> Fix bug of click change scale & wheel change scale

src/parser/my_qsvg_handler.cpp
Update transform with group by add transform map with node name.
Read svg file(winebox.svg)
=> Update transform with group

src/parser/dxf_iface.cpp, src/parser/dxf_iface.h
dxf reader add arc function.
read 無障礙圖示.dxf
=> Add dxf read arc

src/windows/rotary_setup.cpp, src/windows/rotary_setup.h, src/windows/rotary_setup.ui
Change rotary UI to add OK/cancel.
=> change-rotary-UI

src/document-serializer.h, src/widgets/panels/layer-params-panel.cpp, src/widgets/panels/transform-panel.ui
Add backlash to bb file and transform UI range.
Setting backlash and switch layer to check value change.
=> Bug/add backlash to bb and transform UI range

src/canvas/canvas.cpp, src/parser/my_qsvg_handler.cpp
Change scale define in my qsvg.
Input svg unit update at the same time.
=> Change scale define in my qsvg

src/canvas/canvas.cpp, src/canvas/canvas.h
Fix native gesture to change scale small than 10%.
=> Fix native gesture to change scale small than 10%

src/widgets/panels/jogging-panel.ui
Update jogging panel show current.
=> Update jogging panel show current

src/windows/mainwindow.cpp
make sure Widget won't block by other UI when show by action.
=> make sure Widget won't block by other UI when show by action

src/canvas/canvas.cpp, src/canvas/canvas.h, src/windows/mainwindow.cpp
Add mode exit when mode switch.
Input text then switch mode to check text shape added.
=> Add mode exit when mode switch

src/toolpath_exporter/generators/dirty-area-outline-generator.h, src/toolpath_exporter/generators/gcode-generator.h, src/toolpath_exporter/generators/preview-generator.h, src/toolpath_exporter/toolpath-exporter.cpp, src/toolpath_exporter/toolpath-exporter.h, src/widgets/panels/layer-params-panel.ui, src/widgets/panels/transform-panel.ui, src/windows/mainwindow.cpp, src/windows/preview-window.cpp, src/windows/preview-window.h, src/windows/rotary_setup.cpp
Add rotary mirror function and change shape position by rotary period.
Input image and open rotary function to check mirror by preview.
=> Add rotary mirror function

src/parser/pdf2svg.cpp
Fix filepath with non ascii char.
=> Fix filepath with non ascii char

src/executor/machine_setup_executor.cpp
Send a soft reset before any command to handle the situation that machine is in hold state
=> Set soft reset as the first cmd when connecting

src/settings/preset-settings.h, src/widgets/panels/image-panel.ui, src/widgets/panels/laser-panel.ui, src/windows/rotary_setup.cpp, src/windows/rotary_setup.h, src/windows/rotary_setup.ui
Update rotary setting UI, doc panel preset default power, and laser panel UI.
=> Feature/update UI

src/widgets/panels/laser-panel.ui
=> Update laser panel min size

src/windows/mainwindow.cpp
Add pdf and ai drop. Fix svg drop size.
Drop pdf and svg file to test.
=> Add pdf and ai drop. Fix svg drop size

src/windows/about-window.ui
Enable about to link git.
Use about UI to open git web.
=> Enable about to link git

.github/workflows/build-win64-msvc.yml, .github/workflows/generate_appcast.yml, CMakeLists.txt, src/parser/qsvggraphics_p.h, swiftray.pro
=> Version update to v1.1.3

src/windows/rotary_setup.cpp
Add update rotary scale when enable rotary mode.
=> Add update rotary scale when enable rotary mode

src/parser/my_qsvg_handler.cpp, src/parser/my_qsvg_handler.h
Add svg handle when shape is hiden.
=> Add svg handle when shape is hiden

src/windows/mainwindow.cpp
Refine the release version of Swiftray shown on sentry.io
=> Refine app release version shown on sentry

.github/workflows/build-release.yml, src/settings/machine-settings.cpp
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Change git build mac os to 11
